# Everything in this section will be available as an environment variable
[postgres]
host = "127.0.0.1"
port = 5435
dbname = "xgpt"
user = "xgpt"
password = "xgpt"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment
# variables, but they'll be easily accessible from within Streamlit anyway
# as we show later in this doc.
[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]
