aleph_alpha_completion:
  model: "luminous-extended-control"
  temperature: 0
  max_tokens: 200
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  best_of: 1
  repetition_penalties_include_prompt: True
  stop_sequences: "###"
  repetition_penalties_include_completion: True
