version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: xgpt
      POSTGRES_PASSWORD: xgpt
      POSTGRES_DB: xgpt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5435:5432"

volumes:
  postgres-data:
