wtf:
  colors:
    background: "red"
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
    checked: "gray"
    highlight:
      fore: "black"
      back: "green"
    text: "white"
    title: "white"
  exitMessage:
    display: true
    githubAPIKey: "d8....................................ea"
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # six columns, each of which are 35 characters wide
    columns: [35, 35, 35, 35, 35, 35]

    # How _high_ the rows are, in terminal lines. In this case we have five rows
    # that support ten line of text, one of three lines, and one of four
    rows: [10, 10, 10, 10, 10, 3, 4]
  navigation:
    shortcuts: true
  openFileUtil: "open"
  openUrlUtil:
    - "tmux"
    - "new-window"
    - "elinks"
  sigils:
    checkbox:
      checked: "x"
      unchecked: " "
    paging:
      normal: "*"
      selected: "_"
  term: "xterm-256color"
  mods:
    # To Do List
    work_todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 2
        height: 2
        width: 2
      refreshInterval: 1h
      type: todo
    # Docker informations
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 0
        left: 0
        height: 3
        width: 3
      refreshInterval: 1s
