name: Run tests

on:
  workflow_dispatch:
  push:
    paths:
      - "pytermgui/**"
      - "tests/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install testfixtures
          pip install pytest-cov
          pip install coverage
          pip install pyyaml
          pip install .

      - name: Run tests with coverage
        run: |
          make test
