version: '3.5'
services:
    gpt-pilot:
        environment:
            #OPENAI or AZURE
            - ENDPOINT=OPENAI 
            - OPENAI_API_KEY=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
            # - AZURE_API_KEY=
            # - AZURE_ENDPOINT=
            #In case of Azure endpoint, change this to your deployed model name
            - MODEL_NAME=gpt-4
            - MAX_TOKENS=8192
            - DATABASE_TYPE=postgres
            - DB_NAME=pilot
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=pilot
            - DB_PASSWORD=pilot
        image: ax2l/xgpt-pilot:latest
        volumes:
            - ./workspace:/usr/src/app/workspace
        ports:
            - "7681:7681"
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: pilot
            POSTGRES_PASSWORD: pilot
            POSTGRES_DB: pilot
        ports:
        - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pilot"]
            interval: 30s
            timeout: 10s
            retries: 3
